name: luna
description: "Minimalistic news app powered by The Guardian API"
publish_to: "none"
version: 1.2.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  desktop_window: ^0.4.2
  msix: ^3.16.8
  material_symbols_icons: ^4.2815.0
  html_unescape: ^2.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  flutter_html: ^3.0.0
  google_fonts: ^6.2.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

flutter:
  uses-material-design: true

msix_config:
  display_name: Luna
  publisher_display_name: AS
  identity_name: com.as.project-luna
  msix_version: 1.2.1.0
  logo_path: windows/runner/resources/app_icon.ico
